// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiNHlsoEyAhrUdxA_X7SyXWH90No5-EEQ',
    appId: '1:994455466970:web:7e5aac98ced9c4784206e3',
    messagingSenderId: '994455466970',
    projectId: 'instagram-clone-c8c4a',
    authDomain: 'instagram-clone-c8c4a.firebaseapp.com',
    storageBucket: 'instagram-clone-c8c4a.appspot.com',
    measurementId: 'G-YS6B3NEPK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXAL15DsYij7C559L0AC4o1vnNV_MZMHk',
    appId: '1:994455466970:android:b39dbab13bd53cb74206e3',
    messagingSenderId: '994455466970',
    projectId: 'instagram-clone-c8c4a',
    storageBucket: 'instagram-clone-c8c4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrWBPgjwflVfEVT_sr78HaZskelfSaCY',
    appId: '1:994455466970:ios:2ebce9880adb44074206e3',
    messagingSenderId: '994455466970',
    projectId: 'instagram-clone-c8c4a',
    storageBucket: 'instagram-clone-c8c4a.appspot.com',
    iosClientId: '994455466970-ftla4umu4mqosbjvkp6fkgfqc8uj40j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRrWBPgjwflVfEVT_sr78HaZskelfSaCY',
    appId: '1:994455466970:ios:2ebce9880adb44074206e3',
    messagingSenderId: '994455466970',
    projectId: 'instagram-clone-c8c4a',
    storageBucket: 'instagram-clone-c8c4a.appspot.com',
    iosClientId: '994455466970-ftla4umu4mqosbjvkp6fkgfqc8uj40j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone',
  );
}
